#!/usr/bin/env Rscript

# -----------------------------------------------------------------------------
# makeL1RankTable.r #NAMING
#
# This script creates a separate R data file containing a data frame with columns:
#	L1 Chromosome
#	L1 Start
#	L1 End
#	L1 Bit score with Brouha et al. Hot L1 consensus
#	L1 Strand
#
#
# The file generated by this script is required by process_L1s.r
# 
# Usage: ./makeL1RankTable.r <score file>, <l1base file>, <output image filename>
# Output: <output image filename> to data directory.
#
# Dependencies: R(>= 2.8.0, Packages - Biostrings, data.table)
# -----------------------------------------------------------------------------

library(Biostrings)
library(data.table)

args=commandArgs(trailingOnly=TRUE)

scoreTab <- read.table(args[1])
l1baseTab <- read.table(args[2])
L1RankTable<-data.table(
variable1=l1baseTab[,1][scoreTab[,1]],
variable2=l1baseTab[,2][scoreTab[,1]]+scoreTab[,2]-1,
variable3=l1baseTab[,2][scoreTab[,1]]+scoreTab[,3]-1
)
names(L1RankTable)<-c("chr","start","end")
L1RankTable$score <- scoreTab[,4]
L1RankTable$strand <- scoreTab[,5]
save(L1RankTable,file=args[3])
